---
abstract: "Redefine a Linux console's color palette"
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ConPalette
no_index:
  directory:
    - t
    - utils
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-ConPalette
  homepage: http://metacpan.org/release/App-ConPalette
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/app-conpalette.git
version: 0.1.7
x_authority: cpan:HINRIK
